org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.16
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=usefulvillagers
mod_name=Useful Villagers
mod_license=MIT
mod_version=1.20.1-FGE-1.6
mod_group_id=me.kctops6
mod_authors=KCtops6
mod_description=A mod that makes villagers more productive and useful in your world.