modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="usefulvillagers"
version="1.5.1"
displayName="Useful Villagers"
authors="KCtops6"
description='''
Makes villagers more useful by allowing manual inventory management and automated task handling.
'''

[[dependencies.usefulvillagers]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.usefulvillagers]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"